apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongodump-job2
spec:
  schedule: "30 19 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mongodump-job2
            image: bitnami/mongodb
            command: ["mongodump"]
            volumeMounts:
            - mountPath: "/dump"
              name: mongodump
          volumes:
          - name: mongodump
            persistentVolumeClaim:
              claimName: mongo-pvc
          restartPolicy: OnFailure
